spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://user-service-mariadb:3306/mydb
    username: root
    password: '{cipher}AQBibGb2+cmzRCKJOk+J3QlC5VKUrXoKeKBiSYbL/t5CeVURNcVB2s4nC9gkDEgPYHQByEVaI8Brr8S6dnc2/DFfsmcJIc+MqDAYQmPnHSTwAvBly1wKHfWpKPXr+Cd+tG/FxSKGqb0Fj71YK8sWJYQGcP00Jn8dRbKs7QinAjNfJdXWoTlU/1OXti5XH9JhwYq8aSEY2VwcbsZlLOSneorjGl5xcpAG53ZiJ3VmnSD2ndeMjnCyhiVdoKoUIr6jilgPMz2MuErEmuuUl5VKaHY3PC79j6N96/VWMheZ9fIYNQf7x8WYObtA491nuvCcSF3+HzyO47vXfujYuxwRsHJYNeyvLOKIfxJViqgeiI27s0s93sZgZGXCBQcItQI9TCQ='
token:
  expiration_time: 86400000
  secret: '{cipher}AQAoWRjz24elU9b/CEnG8VGgDcG3Xczt+aELQEwTD51OYeAMpLHYL+C/8hrZ6Cu0o0JvcojPyRxeOCXcV8RLb3rcXa/IdqXB4RDyAdsfY3azB64Su3xocyJNFWGUWnIdVTUGF7bsrPpYoYloA+SxoYd5TKZ8Pm9vZyBiaSXMZMW/6koiESVS/6vVBXzP7fr06K62sID7QHI2qwKZxurlygSbIy/tilh0Soj/t/NBtNQaGvKrYBhMAUmIxvNKl5Pb6dbnFwyFb1/D7xBUYXmtHxRGlCcOwHtPEbLqnYLDvXrFBPj+JRg3JijDIBt2V101tzqkAz18QWKbXVjShMFb4+uK3r13/TT/H3svREPoKaK7ajgysvX++KwJoqMP3VG1Qw5oAd4hVElwux17tyw0mIRYTYuVfM2KUwoJ0rIPXttjJA=='

gateway:
  ip: apigateway-service

order_service:
  url: http://apigateway-service:8000/order-service/%s/orders
  exception: 
    orders_is_empty: User's order is empty.
