spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://user-service-mariadb:3306/mydb
    username: root
    password: '{cipher}AQBibGb2+cmzRCKJOk+J3QlC5VKUrXoKeKBiSYbL/t5CeVURNcVB2s4nC9gkDEgPYHQByEVaI8Brr8S6dnc2/DFfsmcJIc+MqDAYQmPnHSTwAvBly1wKHfWpKPXr+Cd+tG/FxSKGqb0Fj71YK8sWJYQGcP00Jn8dRbKs7QinAjNfJdXWoTlU/1OXti5XH9JhwYq8aSEY2VwcbsZlLOSneorjGl5xcpAG53ZiJ3VmnSD2ndeMjnCyhiVdoKoUIr6jilgPMz2MuErEmuuUl5VKaHY3PC79j6N96/VWMheZ9fIYNQf7x8WYObtA491nuvCcSF3+HzyO47vXfujYuxwRsHJYNeyvLOKIfxJViqgeiI27s0s93sZgZGXCBQcItQI9TCQ='
token:
  expiration_time: 86400000
  secret: '{cipher}AQBspJnRyATMJGCDOfP9YtdfjUFTLhcWpx7oLO6Z0P9ZsgkDvdRNFnT2QoeaVBiNzDYnhqOafA8uMsOuYfy9hEQWqydNEW/AgCdW8dgAoJPZgH1oHmbARdrXT59dPuzRPE28uK1jgI1V6fIZytN/JSgZ/xu6Uq5h1I+KO6dzxTDuQO0qbrM4nggQ1heKpIUSw67WHGAKK1p7sjHXxjGa2+L9cWz1RCybqGhvmqUz31h0Cz4I68QeBZ2dNpBZOyu8Vo5WtmVM9MIvgadx5IwYwsT1Ry/Zegab/bKtKzqbW5BQO8kH5umwedp20VuFYx7a6uFuwG696hWIHsNH/33z2NZdO4ULHbWcN2TxzItiBgK16cG+57lmVZ/x+w9wgd0eOGA='

gateway:
  ip: apigateway-service

order_service:
  url: http://apigateway-service:8000/order-service/%s/orders
  exception: 
    orders_is_empty: User's order is empty.
