spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://user-service-mariadb:3306/mydb
    username: root
    password: '{cipher}AQBibGb2+cmzRCKJOk+J3QlC5VKUrXoKeKBiSYbL/t5CeVURNcVB2s4nC9gkDEgPYHQByEVaI8Brr8S6dnc2/DFfsmcJIc+MqDAYQmPnHSTwAvBly1wKHfWpKPXr+Cd+tG/FxSKGqb0Fj71YK8sWJYQGcP00Jn8dRbKs7QinAjNfJdXWoTlU/1OXti5XH9JhwYq8aSEY2VwcbsZlLOSneorjGl5xcpAG53ZiJ3VmnSD2ndeMjnCyhiVdoKoUIr6jilgPMz2MuErEmuuUl5VKaHY3PC79j6N96/VWMheZ9fIYNQf7x8WYObtA491nuvCcSF3+HzyO47vXfujYuxwRsHJYNeyvLOKIfxJViqgeiI27s0s93sZgZGXCBQcItQI9TCQ='
token:
  expiration_time: 86400000
  secret: '{cipher}AQCrzImM/Bun2r2+yE2L2rjTWV8QqnzDfGh0W0RJpOtHsDFYfvey2yXfbGgkg0IaEeWqADKEOkhL8YoYwGswKf4loXtfkeLFl7d/aMtPyj0DykZF9NkmRmHnsQArNDsZwRhtS0rjBGf7x5P5UtK6Hz8cb4I8UNXYsjk/QK33LuBTiplUiTr7OhN1nuG32h9g+aTCyyeHFEhjbcFCjZE3MM9eb9D+xJsIYFg/zw3OLwnMQ+bYlwPCVREjw570iaJTryCNoMNZCpoWcMi92Sa/RJYMLrxWhlIkNx9ezLleBKmWC8HE2awac0tBK1GbRBxq1UzJ78vx0gWxXh1nb/OnEEB7gM+rVxNp/XLYabJTXndHxbTyKVfshiGn9spxCfz+Iks='

gateway:
  ip: apigateway-service

order_service:
  url: http://apigateway-service:8000/order-service/%s/orders
  exception: 
    orders_is_empty: User's order is empty.
