spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://user-service-mariadb:3306/mydb
    username: root
    password: '{cipher}AQBibGb2+cmzRCKJOk+J3QlC5VKUrXoKeKBiSYbL/t5CeVURNcVB2s4nC9gkDEgPYHQByEVaI8Brr8S6dnc2/DFfsmcJIc+MqDAYQmPnHSTwAvBly1wKHfWpKPXr+Cd+tG/FxSKGqb0Fj71YK8sWJYQGcP00Jn8dRbKs7QinAjNfJdXWoTlU/1OXti5XH9JhwYq8aSEY2VwcbsZlLOSneorjGl5xcpAG53ZiJ3VmnSD2ndeMjnCyhiVdoKoUIr6jilgPMz2MuErEmuuUl5VKaHY3PC79j6N96/VWMheZ9fIYNQf7x8WYObtA491nuvCcSF3+HzyO47vXfujYuxwRsHJYNeyvLOKIfxJViqgeiI27s0s93sZgZGXCBQcItQI9TCQ='
token:
  expiration_time: 86400000
  secret: '{cipher}AQCWOOw0vNvg1ZjEtAnLkNfyA+1YfduEEWgV9TJSlQ5TBh36mFc7wzeqfee2AO8XUyV608IKAQK4HGivDAzWIfJnhtVb1Rd4sqEQysHUsuxjTxiwzBUfjEjqU+nEYsk1fsNhoa7cdCxhpz+vJdDZ7PTOfRF9+ZhT+U5FvuSbs7rdfgmK/S4HsgVPihDQ5yKKumSKNG9O6GCIggbfnqLs3nHpw9pCmjExJ+SNRhRHP8XcCSFlKJWNK6qQ3B89GvRMsYxyc30YRdCoAM+ZLSWKbqMwklYU9ze0XEzCfwlCeBqdCIjYS8YQjJeZ+SgWRIWcHybx/TrVLsW48cj+++EqCrZi1Y+zC32hFEqCWqLOsoQ+rbiso5V1whyTl0Ix4ksCL4TxXRuESu/7YTuTy0sqKkvrt6TxhAV3HlBzQgpHjqWmF0FcBAW9YeuhoIFH1NzMpjYJWdqabXop9kl5UAMrWDEh/yVzBuiC6aDmCBj1jLXxO3ynpXG7RzI5mfk1vPUr0aakUYhB3iCRL+/YXow/H8KW32Zmci3k5K82cNiTEk50jA=='

gateway:
  ip: apigateway-service

order_service:
  url: http://apigateway-service:8000/order-service/%s/orders
  exception: 
    orders_is_empty: User's order is empty.
